import js from '@eslint/js'
import svelte from 'eslint-plugin-svelte'
import prettier from 'eslint-config-prettier'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs['flat/recommended'],
  prettier,
  ...svelte.configs['flat/prettier'],
  {
    languageOptions: {
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {
      // TypeScript (via svelte-check/tsc) already catches undefined
      // references with full type information; the core rule has no
      // knowledge of ambient DOM types like `SubmitEvent`.
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // src/lib/components/ui/** is vendored shadcn-svelte, generated by its
    // CLI and not hand-edited (see foundational/DESIGN.md → Components) -
    // same reasoning as its vitest.config.ts coverage exclusion. Several of
    // its generated files trigger svelte/valid-compile's
    // custom_element_props_identifier rule (a spread-props pattern the
    // generator itself uses), which isn't something to "fix" in code we
    // don't hand-maintain.
    ignores: ['build/', '.svelte-kit/', 'dist/', 'coverage/', 'src/lib/components/ui/'],
  }
)
