/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'isActive',
    'name',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = CategorySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecurringBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'customIntervalUnit',
    'customIntervalValue',
    'dueDay',
    'dueMonth',
    'dueYear',
    'frequency',
    'id',
    'isActive',
    'name',
    'nextDueOn',
    'notes',
    'updatedAt',
  ] as const
  $columns = RecurringBillSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customIntervalUnit: string | null
  @column()
  declare customIntervalValue: number | null
  @column()
  declare dueDay: number | null
  @column()
  declare dueMonth: number | null
  @column()
  declare dueYear: number | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.date()
  declare nextDueOn: DateTime | null
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'displayColor',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayColor: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilitySchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = UtilitySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilityBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'month',
    'notes',
    'updatedAt',
    'utilityId',
    'year',
  ] as const
  $columns = UtilityBillSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare utilityId: number
  @column()
  declare year: number
}
