/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = [
    'budgetAmount',
    'color',
    'createdAt',
    'id',
    'includeInStandardMonth',
    'isActive',
    'isArchived',
    'isPaused',
    'name',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = CategorySchema.$columns
  @column()
  declare budgetAmount: number | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeInStandardMonth: boolean
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoryBudgetItemSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'id',
    'name',
    'notes',
    'updatedAt',
  ] as const
  $columns = CategoryBudgetItemSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoryMonthlyActualSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'id',
    'notes',
    'occurredOn',
    'updatedAt',
  ] as const
  $columns = CategoryMonthlyActualSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare occurredOn: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategoryPaymentSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'month', 'paid', 'updatedAt', 'year'] as const
  $columns = CategoryPaymentSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class IncomeEntrySchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'incomeSourceId',
    'month',
    'note',
    'receivedOn',
    'taxWithheld',
    'updatedAt',
    'userId',
    'year',
  ] as const
  $columns = IncomeEntrySchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incomeSourceId: number | null
  @column()
  declare month: number
  @column()
  declare note: string | null
  @column.date()
  declare receivedOn: DateTime | null
  @column()
  declare taxWithheld: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare year: number
}

export class IncomeSourceSchema extends BaseModel {
  static $columns = [
    'anchorDate',
    'createdAt',
    'expectedAmount',
    'frequency',
    'id',
    'isActive',
    'name',
    'notes',
    'payDayOfMonth',
    'taxWithheld',
    'updatedAt',
    'userId',
    'weekendRollback',
  ] as const
  $columns = IncomeSourceSchema.$columns
  @column.date()
  declare anchorDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expectedAmount: number
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare payDayOfMonth: number | null
  @column()
  declare taxWithheld: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare weekendRollback: boolean
}

export class IncomeTaxSettingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'financialYear',
    'id',
    'marginalRate',
    'updatedAt',
    'userId',
  ] as const
  $columns = IncomeTaxSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare financialYear: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marginalRate: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MonthCarryoverSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'month', 'notes', 'updatedAt', 'year'] as const
  $columns = MonthCarryoverSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class RecurringBillPaymentSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'month',
    'paid',
    'recurringBillId',
    'updatedAt',
    'year',
  ] as const
  $columns = RecurringBillPaymentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column()
  declare recurringBillId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class RecurringBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'customIntervalUnit',
    'customIntervalValue',
    'dueDay',
    'dueMonth',
    'dueYear',
    'frequency',
    'id',
    'isActive',
    'isArchived',
    'isPaused',
    'name',
    'nextDueOn',
    'notes',
    'updatedAt',
  ] as const
  $columns = RecurringBillSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customIntervalUnit: string | null
  @column()
  declare customIntervalValue: number | null
  @column()
  declare dueDay: number | null
  @column()
  declare dueMonth: number | null
  @column()
  declare dueYear: number | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare name: string
  @column.date()
  declare nextDueOn: DateTime | null
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionPaymentSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'month',
    'paid',
    'updatedAt',
    'userSubscriptionId',
    'year',
  ] as const
  $columns = SubscriptionPaymentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userSubscriptionId: number
  @column()
  declare year: number
}

export class UserSubscriptionSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'dayOfMonth',
    'id',
    'includeInStandardMonth',
    'isActive',
    'isArchived',
    'isPaused',
    'name',
    'notes',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserSubscriptionSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfMonth: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeInStandardMonth: boolean
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'displayColor',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayColor: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilitySchema extends BaseModel {
  static $columns = [
    'categoryId',
    'createdAt',
    'dueOffsetDays',
    'frequency',
    'id',
    'isActive',
    'name',
    'updatedAt',
  ] as const
  $columns = UtilitySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dueOffsetDays: number | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilityBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'month',
    'notes',
    'paid',
    'updatedAt',
    'utilityId',
    'year',
  ] as const
  $columns = UtilityBillSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare notes: string | null
  @column()
  declare paid: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare utilityId: number
  @column()
  declare year: number
}
