/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BackupSettingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enabled',
    'id',
    'intervalHours',
    'lastRunAt',
    'retentionDays',
    'runHour',
    'updatedAt',
  ] as const
  $columns = BackupSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare intervalHours: number
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare retentionDays: number
  @column()
  declare runHour: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'isActive',
    'isArchived',
    'isSystem',
    'name',
    'parentId',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = CategorySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseBudgetItemSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'expenseId',
    'id',
    'name',
    'notes',
    'updatedAt',
  ] as const
  $columns = ExpenseBudgetItemSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expenseId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpenseMonthlyActualSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'expenseId',
    'id',
    'notes',
    'occurredOn',
    'updatedAt',
  ] as const
  $columns = ExpenseMonthlyActualSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expenseId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare occurredOn: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExpensePaymentSchema extends BaseModel {
  static $columns = ['createdAt', 'expenseId', 'id', 'month', 'paid', 'updatedAt', 'year'] as const
  $columns = ExpensePaymentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expenseId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class ExpenseSchema extends BaseModel {
  static $columns = [
    'budgetAmount',
    'categoryId',
    'createdAt',
    'excludeFromBudget',
    'id',
    'isActive',
    'isArchived',
    'isPaused',
    'isRecurring',
    'name',
    'sortOrder',
    'updatedAt',
  ] as const
  $columns = ExpenseSchema.$columns
  @column()
  declare budgetAmount: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excludeFromBudget: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare isRecurring: boolean
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IncomeEntrySchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'incomeSourceId',
    'month',
    'note',
    'receivedOn',
    'taxWithheld',
    'updatedAt',
    'userId',
    'year',
  ] as const
  $columns = IncomeEntrySchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare incomeSourceId: number | null
  @column()
  declare month: number
  @column()
  declare note: string | null
  @column.date()
  declare receivedOn: DateTime | null
  @column()
  declare taxWithheld: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare year: number
}

export class IncomeSourceSchema extends BaseModel {
  static $columns = [
    'anchorDate',
    'createdAt',
    'expectedAmount',
    'frequency',
    'id',
    'isActive',
    'name',
    'notes',
    'payDayOfMonth',
    'taxWithheld',
    'updatedAt',
    'userId',
    'weekendRollback',
  ] as const
  $columns = IncomeSourceSchema.$columns
  @column.date()
  declare anchorDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expectedAmount: number
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare payDayOfMonth: number | null
  @column()
  declare taxWithheld: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare weekendRollback: boolean
}

export class IncomeTaxSettingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'financialYear',
    'id',
    'marginalRate',
    'updatedAt',
    'userId',
  ] as const
  $columns = IncomeTaxSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare financialYear: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marginalRate: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MonthCarryoverSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'month', 'notes', 'updatedAt', 'year'] as const
  $columns = MonthCarryoverSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class NotificationScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastRunAt', 'sendHour', 'updatedAt'] as const
  $columns = NotificationScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare sendHour: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushConfigSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'privateKey', 'publicKey', 'subject', 'updatedAt'] as const
  $columns = PushConfigSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare privateKey: string
  @column()
  declare publicKey: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = [
    'auth',
    'createdAt',
    'endpoint',
    'id',
    'p256Dh',
    'updatedAt',
    'userAgent',
    'userId',
  ] as const
  $columns = PushSubscriptionSchema.$columns
  @column()
  declare auth: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare p256Dh: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RecurringBillPaymentSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'month',
    'paid',
    'recurringBillId',
    'updatedAt',
    'year',
  ] as const
  $columns = RecurringBillPaymentSchema.$columns
  @column()
  declare amount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column()
  declare recurringBillId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class RecurringBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'dueDay',
    'dueMonth',
    'dueYear',
    'frequency',
    'id',
    'isActive',
    'isArchived',
    'isPaused',
    'name',
    'notes',
    'updatedAt',
  ] as const
  $columns = RecurringBillSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dueDay: number | null
  @column()
  declare dueMonth: number | null
  @column()
  declare dueYear: number | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionPaymentSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'month',
    'paid',
    'updatedAt',
    'userSubscriptionId',
    'year',
  ] as const
  $columns = SubscriptionPaymentSchema.$columns
  @column()
  declare amount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare paid: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userSubscriptionId: number
  @column()
  declare year: number
}

export class UserNotificationPreferenceSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enabled',
    'id',
    'leadDays',
    'notifyRecurringBills',
    'notifySubscriptions',
    'notifyUtilityBills',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserNotificationPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leadDays: number
  @column()
  declare notifyRecurringBills: boolean
  @column()
  declare notifySubscriptions: boolean
  @column()
  declare notifyUtilityBills: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSubscriptionSchema extends BaseModel {
  static $columns = [
    'amount',
    'categoryId',
    'createdAt',
    'dayOfMonth',
    'id',
    'isActive',
    'isArchived',
    'isPaused',
    'isRecurring',
    'name',
    'notes',
    'updatedAt',
    'userId',
  ] as const
  $columns = UserSubscriptionSchema.$columns
  @column()
  declare amount: number
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfMonth: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isArchived: boolean
  @column()
  declare isPaused: boolean
  @column()
  declare isRecurring: boolean
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'displayColor',
    'email',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayColor: string | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilitySchema extends BaseModel {
  static $columns = [
    'categoryId',
    'createdAt',
    'dueOffsetBusinessDaysOnly',
    'dueOffsetDays',
    'frequency',
    'id',
    'isActive',
    'name',
    'paidInAdvance',
    'updatedAt',
  ] as const
  $columns = UtilitySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dueOffsetBusinessDaysOnly: boolean
  @column()
  declare dueOffsetDays: number | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare paidInAdvance: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UtilityBillSchema extends BaseModel {
  static $columns = [
    'amount',
    'createdAt',
    'id',
    'month',
    'notes',
    'paid',
    'receivedOn',
    'updatedAt',
    'utilityId',
    'year',
  ] as const
  $columns = UtilityBillSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare month: number
  @column()
  declare notes: string | null
  @column()
  declare paid: boolean
  @column.date()
  declare receivedOn: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare utilityId: number
  @column()
  declare year: number
}
